import{DesignDocument,DesignNode}from'./model';
type NewNode=Omit<DesignNode,'id'|'visible'|'locked'>;
const stamp=()=>new Date().toISOString();
export function addNode(d:DesignDocument,n:NewNode):DesignDocument{return{...d,nodes:[...d.nodes,{...n,id:`node-${Date.now()}-${d.nodes.length}`,visible:true,locked:false}],updatedAt:stamp()}}
export function moveNode(d:DesignDocument,id:string,delta:number){const a=[...d.nodes],i=a.findIndex(n=>n.id===id),j=Math.max(1,Math.min(a.length-1,i+delta));if(i<1||i===j)return d;[a[i],a[j]]=[a[j],a[i]];return{...d,nodes:a,updatedAt:stamp()}}
export function toggleNodeVisibility(d:DesignDocument,id:string){return{...d,nodes:d.nodes.map(n=>n.id===id?{...n,visible:!n.visible}:n),updatedAt:stamp()}}
export function toggleNodeLock(d:DesignDocument,id:string){return{...d,nodes:d.nodes.map(n=>n.id===id?{...n,locked:!n.locked}:n),updatedAt:stamp()}}
export function createCheckpoint(d:DesignDocument,label:string){const snapshot=JSON.stringify({...d,versions:[]});return{...d,versions:[...d.versions,{id:`v-${Date.now()}`,label,at:stamp(),snapshot}],updatedAt:stamp()}}
export function rollbackToCheckpoint(d:DesignDocument,id:string){const v=d.versions.find(x=>x.id===id);if(!v?.snapshot)return d;const restored=JSON.parse(v.snapshot)as DesignDocument;const safety={id:`v-${Date.now()}-pre`,label:'回復前備份',at:stamp(),snapshot:JSON.stringify({...d,versions:[]})};return{...restored,versions:[...d.versions,safety],updatedAt:stamp()}}
export function validateBoundary(d:DesignDocument){const text=JSON.stringify(d.runtimeManifest).toLowerCase();const forbidden=['firebase-direct','printer','cashdrawer','nativebridge','business-truth','payment-authority','order-truth'];return forbidden.filter(x=>text.includes(x)).map(x=>`禁止越權：${x}`)}
export function exportCandidate(d:DesignDocument){const errors=validateBoundary(d);if(errors.length)throw new Error(errors.join('\n'));return{document:d,manifest:d.runtimeManifest,contracts:d.contracts,exportedAt:stamp()}}
export function downloadCandidate(d:DesignDocument){const out=exportCandidate(d),blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${d.id}-candidate.json`;a.click();URL.revokeObjectURL(url)}